sudo: required
services:
  - docker

before_install:
  - docker build -t mnouaytid/docker-react -f Dockerfile.dev .

script:
  # - docker run mnouaytid/docker-react npm run test  -- --coverage
  - docker run -e CI=true mnouaytid/docker-react npm run test